In [7]:
import numpy as np
import timeit

In [46]:
#vectors
vA = [5,6,7]
vB = [3,2,3]
np_vA, np_vB= np.array(vA), np.array(vB)
#matrix
mA= [[1,1,1], [1,1,1], [1,1,1]]
mB= [[1,2,1], [3,4,3], [5,6,5]]
np_mA, np_mB= np.matrix(mA), np.matrix(mB)

In [50]:
def scalar_prodact(A, B):
    return sum(x*y for x, y in zip(A, B))

def np_scalar_prodact(A, B):
    return np.dot(A, B)

print(np_scalar_prodact(np_vA, np_vB), scalar_prodact(vA, vB))

# numpy starts to be more effective for array longer then 14 numbers
print(f"Scalar product using numpy: {timeit.timeit(lambda: np_scalar_prodact(np_vA, np_vB), number=100000)}/s for 100000 repeats")
print(f"Scalar product using standart python: {timeit.timeit(lambda: scalar_prodact(vA, vB), number=100000)}/s for 100000 repeats")

48 48
Scalar product using numpy: 0.18201730004511774/s for 100000 repeats
Scalar product using standart python: 0.0935518000042066/s for 100000 repeats


In [49]:
def vector_addition(A, B):
    return [x+y for x,y in zip(A, B)]

def np_vector_addition(A, B):
    return A+B

print(np_vector_addition(np_vA, np_vB), vector_addition(vA, vB))

print(f"Scalar product using numpy: {timeit.timeit(lambda: np_vector_addition(np_vA, np_vB), number=100000)}/s for 100000 repeats")
print(f"Scalar product using standart python: {timeit.timeit(lambda: vector_addition(vA, vB), number=100000)}/s for 100000 repeats")

[ 8  8 10] [8, 8, 10]
Scalar product using numpy: 0.09411329997237772/s for 100000 repeats
Scalar product using standart python: 0.07579359994269907/s for 100000 repeats


In [55]:
def matrix_addition(A, B):
    assert len(A) == len(B) & len(A[0]) == len(B[0]), "Wrong matrix shape"
    x = [[0 for i in range(len(A[0]))] for j in range(len(A))]
    for i in range(len(A)):
        for j in range(len(A[0])):
            x[i][j] = A[i][j] + B[i][j]
    return x

def np_matrix_addition(A, B):
    return A+B

print(np_matrix_addition(np_mA, np_mB), matrix_addition(mA, mB))

print(f"Addition of matrexes using numpy: {timeit.timeit(lambda: np_matrix_addition(np_mA, np_mB), number= 100000)}/s for 100000 repeats")
print(f"Addition of matrexes using standart python: {timeit.timeit(lambda: matrix_addition(mA, mB), number= 100000)}/s for 100000 repeats")    

[[2 3 2]
 [4 5 4]
 [6 7 6]] [2, 3, 2] [4, 5, 4] [6, 7, 6]
Addition of matrexes using numpy: 0.293477899977006/s for 100000 repeats
Addition of matrexes using standart python: 0.4683958999812603/s for 100000 repeats


In [56]:
def matrix_subtraction(A, B):
    assert len(A) == len(B) & len(A[0]) == len(B[0]), "Wrong matrix shape"
    x = [[0 for i in range(len(A[0]))] for j in range(len(A))]
    for i in range(len(A)):
        for j in range(len(A[0])):
            x[i][j] = A[i][j] - B[i][j]
    return x

def np_matrix_subtraction(A, B):
    return A-B

print(np_matrix_subtraction(np_mA, np_mB), matrix_subtraction(mA, mB))

print(f"Substraction of matrexes using numpy: {timeit.timeit(lambda: np_matrix_subtraction(np_mA, np_mB), number= 100000)}/s for 100000 repeats")
print(f"Substraction of matrexes using standart python: {timeit.timeit(lambda: matrix_subtraction(mA, mB), number= 100000)}/s for 100000 repeats")

[[ 0 -1  0]
 [-2 -3 -2]
 [-4 -5 -4]] [[0, -1, 0], [-2, -3, -2], [-4, -5, -4]]
Substraction of matrexes using numpy: 0.2876343000680208/s for 100000 repeats
Substraction of matrexes using standart python: 0.4613460999680683/s for 100000 repeats


In [57]:
def matrix_multiply(A, B):
    assert len(A) == len(B[0]), "Rows are not equal to columns!"
    x = [[0 for i in range(len(B[0]))] for j in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(A[0])):
                x[i][j] += A[i][k] * B[k][j]
    return x

def np_matrix_multiply(A, B):
    return A*B

print(np_matrix_multiply(np_mA, np_mB), matrix_multiply(mA, mB))

print(f"Multiplication of matrixes using numpy: {timeit.timeit(lambda: np_matrix_multiply(np_mA, np_mB), number= 100000)}/s for 100000 repeats")
print(f"Multiplication of matrixes using standart python: {timeit.timeit(lambda: matrix_multiply(mA, mB), number= 100000)}/s for 100000 repeats")

[[ 9 12  9]
 [ 9 12  9]
 [ 9 12  9]] [[9, 12, 9], [9, 12, 9], [9, 12, 9]]
Multiplication of matrixes using numpy: 0.6756167999701574/s for 100000 repeats
Multiplication of matrixes using standart python: 1.1128971999278292/s for 100000 repeats
